# Check wwinp from LP#14 results

dvp 2026-02-10

In [1]:
import sys

from pathlib import Path

print("Python", sys.version, "at", sys.prefix)

Python 3.14.3 (main, Feb  3 2026, 22:52:18) [Clang 21.1.4 ] at /home/dvp/dev/mckit-meshes/.venv


In [20]:
import numpy as np

In [3]:
import mckit_meshes as mm
from mckit_meshes import ParticleKind
from mckit_meshes import FMesh
from mckit_meshes import WgtMesh

In [4]:
print(mm.__version__)

0.3.1.dev10


In [5]:
ROOT = Path("/mnt/amarano-2tb/yandex/1-projects/LP#14/D3_MCNP_models&results/11_N2_1E5_section7/11_N2_1E5_compA")

In [6]:
assert ROOT.is_dir()

In [7]:
!ls "{ROOT}"

20251010202725_input.i	   irr_sa2  reac_sa2
20251010202725_input.outp  meshtal  wwinp


In [8]:
inp = ROOT / "wwinp"

In [9]:
assert inp.is_file()

In [10]:
with inp.open() as fid:
    weights = WgtMesh.read(fid)

In [11]:
weights.ibins

array([ 200.,  210.,  220.,  230.,  240.,  250.,  260.,  270.,  280.,
        290.,  300.,  310.,  320.,  330.,  340.,  350.,  360.,  370.,
        380.,  390.,  400.,  410.,  420.,  430.,  440.,  450.,  460.,
        470.,  480.,  490.,  500.,  510.,  520.,  530.,  540.,  550.,
        560.,  570.,  580.,  590.,  600.,  610.,  620.,  630.,  640.,
        650.,  660.,  670.,  680.,  690.,  700.,  710.,  720.,  730.,
        740.,  750.,  760.,  770.,  780.,  790.,  800.,  810.,  820.,
        830.,  840.,  850.,  860.,  870.,  880.,  890.,  900.,  910.,
        920.,  930.,  940.,  950.,  960.,  970.,  980.,  990., 1000.,
       1010., 1020., 1030., 1040., 1050., 1060., 1070., 1080., 1090.,
       1100., 1110., 1120., 1130., 1140., 1150., 1160., 1170., 1180.,
       1190., 1200., 1210., 1220., 1230., 1240., 1250., 1260., 1270.,
       1280., 1290., 1300., 1310., 1320., 1330., 1340., 1350., 1360.,
       1370., 1380., 1390., 1400., 1410., 1420., 1430., 1440., 1450.,
       1460., 1470.,

In [12]:
weights.jbins

array([-500., -490., -480., -470., -460., -450., -440., -430., -420.,
       -410., -400., -390., -380., -370., -360., -350., -340., -330.,
       -320., -310., -300., -290., -280., -270., -260., -250., -240.,
       -230., -220., -210., -200., -190., -180., -170., -160., -150.,
       -140., -130., -120., -110., -100.,  -90.,  -80.,  -70.,  -60.,
        -50.,  -40.,  -30.,  -20.,  -10.,    0.,   10.,   20.,   30.,
         40.,   50.,   60.,   70.,   80.,   90.,  100.,  110.,  120.,
        130.,  140.,  150.,  160.,  170.,  180.,  190.,  200.,  210.,
        220.,  230.,  240.,  250.,  260.,  270.,  280.,  290.,  300.,
        310.,  320.,  330.,  340.,  350.,  360.,  370.,  380.,  390.,
        400.,  410.,  420.,  430.,  440.,  450.,  460.,  470.,  480.,
        490.,  500.])

In [13]:
weights.kbins

array([-1200., -1190., -1180., -1170., -1160., -1150., -1140., -1130.,
       -1120., -1110., -1100., -1090., -1080., -1070., -1060., -1050.,
       -1040., -1030., -1020., -1010., -1000.,  -990.,  -980.,  -970.,
        -960.,  -950.,  -940.,  -930.,  -920.,  -910.,  -900.,  -890.,
        -880.,  -870.,  -860.,  -850.,  -840.,  -830.,  -820.,  -810.,
        -800.,  -790.,  -780.,  -770.,  -760.,  -750.,  -740.,  -730.,
        -720.,  -710.,  -700.,  -690.,  -680.,  -670.,  -660.,  -650.,
        -640.,  -630.,  -620.,  -610.,  -600.,  -590.,  -580.,  -570.,
        -560.,  -550.,  -540.,  -530.,  -520.,  -510.,  -500.,  -490.,
        -480.,  -470.,  -460.,  -450.,  -440.,  -430.,  -420.,  -410.,
        -400.,  -390.,  -380.,  -370.,  -360.,  -350.,  -340.,  -330.,
        -320.,  -310.,  -300.,  -290.,  -280.,  -270.,  -260.,  -250.,
        -240.,  -230.,  -220.,  -210.,  -200.,  -190.,  -180.,  -170.,
        -160.,  -150.,  -140.,  -130.,  -120.,  -110.,  -100.,   -90.,
      

In [14]:
weights.count_parts

1

In [16]:
energies, data = weights.part(ParticleKind.neutron)

In [17]:
energies

array([ 0., 50.])

In [18]:
data.min(), data.max()

(np.float64(0.0), np.float64(0.574456))

In [19]:
data.shape, weights.ibins.size, weights.jbins.size, weights.kbins.size

((1, 150, 100, 240), 151, 101, 241)

In [31]:
errors = np.ones_like(data)*0.1

In [27]:
errors.max()

np.float64(2224.271693195243)

In [32]:
fmesh = FMesh(4, ParticleKind.neutron, weights.geometry_spec, energies, data, errors) 

In [36]:
fmesh.save2vtk(str(inp), data_name="wwinp, n")

'/mnt/amarano-2tb/yandex/1-projects/LP#14/D3_MCNP_models&results/11_N2_1E5_section7/11_N2_1E5_compA/wwinp.vtr'